# Usa a imagem oficial do PHP com Apache integrada
FROM php:8.2-apache

# Instala dependências do sistema e ferramentas de desenvolvimento
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libpq-dev \
    libzip-dev

# Limpa os arquivos temporários do gerenciador de pacotes para diminuir o tamanho da imagem
RUN apt-get clean && rm -rf /var/am/lists/*

# Instala extensões PHP essenciais para o Laravel, PostgreSQL e processamento de arquivos (fileinfo)
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql mbstring exif pcntl bcmath gd zip fileinfo

# Ativa o módulo mod_rewrite do Apache para o Laravel conseguir gerenciar as rotas amigáveis
RUN a2enmod rewrite

# Altera a raiz do servidor Apache para apontar para a pasta public do Laravel
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Copia o Composer de sua imagem oficial para dentro do nosso container
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Define o diretório de trabalho padrão do Apache
WORKDIR /var/www/html

# Copia todos os arquivos do projeto para o container
COPY . /var/www/html

# Altera para o usuário root para executar tarefas administrativas com segurança
USER root

# Limpa o cache do Composer e instala as dependências de produção sem travar os scripts
RUN composer clear-cache
RUN composer install --no-interaction --optimize-autoloader --no-dev

# Garante que o Laravel limpe qualquer cache de configuração antigo que esconde as variáveis do Render
RUN php artisan config:clear
RUN php artisan cache:clear

# Define o dono e o grupo corretos para as pastas cruciais de escrita do Apache/Laravel
RUN chown -R www-data:www-data /var/www/html/vendor /var/www/html/storage /var/www/html/bootstrap/cache
RUN chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

# Expõe a porta padrão do container Apache
EXPOSE 80